logging:
  level:
    root: INFO
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS,Europe/Stockholm
  file:
    name: logs/application.log
server:
  port: 5160
  tomcat:
    basedir: logs
    accesslog:
      enabled: true
      prefix: access
      suffix: .log
      file-date-format: .yyyy-MM-dd
      directory: tomcat
      pattern: common
spring:
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
#    driver-classname: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  config:
    import: application-local.yml

