version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: product_catalogue
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: local
    ports:
      - "5432:5432"